### ISSUE TITLE
Question: Different `-boot` options

### ISSUE THREAD

**Issue by slaff** [raburton/esptool2#1]
I am trying to understand the difference between the boot modes in more detail and will be very thankful if someone can shed some light here.

1. Boot = 0 
Says that it creates a standalone application.
I have seen the testload scripts and it seems that we can implement the entry point function and load code from other SPI Flash locations.  But would it be possible to create a 1MB ROM with libraries inside, use the default `call_user_start` from `libmain`, flash it to address 0x0 and expect that it will work? 
2. Boot = 1 
It creates two rom files. One at address 0x0 and the other at the address defined in the LD script for the irom0_0_seg.  If I understood it correctly there is no bootloader added. Is that correct? So we have a sort-of-standalone app again? Why is the ELF file split into two ROMS? 
3. Boot = 2
Creates ROMs with version 1.2+.  Apart from the MagicNumber in the ROM headers what is different in comparison to images create with Boot = 0. Can I flash ROM images with -boot=2 at position 0x0 and expect it to work?

**Comment by raburton** [comment]
Mode 0 is for single, non-bootloaded apps. Mode 1 is for an old version of the sdk bootloader, unlikely anyone will use this mode now. Mode 2 is for the later version of the sdk bootloader and rBoot.
The boot process and the different rom types and headers is quite complicated, but hopefully fairly well explained here: https://richard.burtons.org/2015/05/17/esp8266-boot-process/ & https://richard.burtons.org/2015/05/17/decompiling-the-esp8266-boot-loader-v1-3b3/
